Wallet/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Wallet.Data;
using Wallet.Models;

namespace Wallet.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IStringLocalizer<MyResources> _localizer;

        public TransactionsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IStringLocalizer<MyResources> localizer)
        {
            _context = context;
            _userManager = userManager;
            _localizer = localizer;
        }

        // GET: Transactions
        public async Task<IActionResult> Index()
        {
            var currUserId = _userManager.GetUserId(User);

            var currUser = _context.Users.Include(u => u.TransactionTo).Include(u=>u.TransactionsFrom).First(u => u.Id == currUserId);
            
            return View(currUser);
        }

        // GET: Transactions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction
                .Include(t => t.ApplicationUserFrom)
                .Include(t => t.ApplicationUserTo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // GET: Transactions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Transaction transaction, string userCode)
        {
            var sendTo = _context.Users.FirstOrDefault(u => u.UserName == userCode);
            if (sendTo == null)
            {
                ModelState.AddModelError(string.Empty, _localizer["errMsg2"]);
            }

            var sendFromUserId = _userManager.GetUserId(User);
            var sendFrom = _context.Users.Find(sendFromUserId);
            if (sendFrom.Balance - transaction.TransactionBalance < 0)
            {
                ModelState.AddModelError(string.Empty, _localizer["errMsg1"]);
            }
            if (ModelState.IsValid)
            {
                sendFrom.Balance -= transaction.TransactionBalance;

                sendTo.Balance += transaction.TransactionBalance;

                _context.Update(sendTo);
                _context.Update(sendFrom);
                Transaction newTransaction = new Transaction()
                {
                    TransactionBalance = transaction.TransactionBalance,
                    ApplicationUserFromId = sendFrom.Id,
                    ApplicationUserToId = sendTo.Id,
                    TransactionDate = DateTime.Now
                };
                _context.Add(newTransaction);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction.FindAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserFromId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", transaction.ApplicationUserFromId);
            ViewData["ApplicationUserToId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", transaction.ApplicationUserToId);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TransactionBalance,ApplicationUserFromId,ApplicationUserToId,Id")] Transaction transaction)
        {
            if (id != transaction.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transaction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactionExists(transaction.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserFromId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", transaction.ApplicationUserFromId);
            ViewData["ApplicationUserToId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", transaction.ApplicationUserToId);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction
                .Include(t => t.ApplicationUserFrom)
                .Include(t => t.ApplicationUserTo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transaction = await _context.Transaction.FindAsync(id);
            _context.Transaction.Remove(transaction);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransactionExists(int id)
        {
            return _context.Transaction.Any(e => e.Id == id);
        }

        public IActionResult TopUpBalance()
        {
            return View();
        }
        public async Task<IActionResult> TopUpBalancePost(string userName, decimal amount)
        {
            var user = _context.Users.FirstOrDefault(u => u.UserName == userName);
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, _localizer["errMsg2"]);
            }

            if (ModelState.IsValid)
            {
                user.Balance += amount;
                _context.Update(user);
                await _context.SaveChangesAsync();
                return Redirect(_localizer["redirect"]);
            }

            return RedirectToAction(nameof(TopUpBalance));
        }
    }
}

Wallet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Localizer["wallet"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
@using Microsoft.AspNetCore.Identity
@using Microsoft.Extensions.Localization;
    @inject UserManager<ApplicationUser> UserManager
    @inject SignInManager<ApplicationUser> SignInManager
    @inject IStringLocalizer<MyResources> Localizer

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Wallet</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["home"]</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Transactions" asp-action="Create">@Localizer["money"]</a></li>
                    }
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Transactions" asp-action="Index">@Localizer["transactions"]</a></li>
                    }
                    @if (SignInManager.IsSignedIn(User))
                    {
                        string userName = UserManager.GetUserName(User);
                        ApplicationUser user = await UserManager.FindByNameAsync(userName);
                        decimal userBalance = user.Balance;
                        <li style="margin-top: 15px; color: red;">Ballance: @userBalance</li>
                    }
                    @if (!SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Transactions" asp-action="TopUpBalance">@Localizer["topUp"]</a></li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Wallet</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>